package bnc

type FilterType string

// https://developers.binance.com/docs/binance-spot-api-docs/filters

const (
	// Symbol filters
	FILTER_TYPE_PRICE_FILTER           FilterType = "PRICE_FILTER"
	FILTER_TYPE_PERCENT_PRICE          FilterType = "PERCENT_PRICE"
	FILTER_TYPE_PERCENT_PRICE_BY_SIDE  FilterType = "PERCENT_PRICE_BY_SIDE"
	FILTER_TYPE_LOT_SIZE               FilterType = "LOT_SIZE"
	FILTER_TYPE_MIN_NOTIONAL           FilterType = "MIN_NOTIONAL"
	FILTER_TYPE_NOTIONAL               FilterType = "NOTIONAL"
	FILTER_TYPE_ICEBERG_PARTS          FilterType = "ICEBERG_PARTS"
	FILTER_TYPE_MAX_NUM_ORDERS         FilterType = "MAX_NUM_ORDERS"
	FILTER_TYPE_MAX_NUM_ALGO_ORDERS    FilterType = "MAX_NUM_ALGO_ORDERS"
	FILTER_TYPE_MAX_NUM_ICEBERG_ORDERS FilterType = "MAX_NUM_ICEBERG_ORDERS"
	FILTER_TYPE_MAX_POSITION           FilterType = "MAX_POSITION"
	FILTER_TYPE_TRAILING_DELTA         FilterType = "TRAILING_DELTA"
	// Exchange filters
	FILTER_TYPE_EXCHANGE_MAX_NUM_ORDERS         FilterType = "EXCHANGE_MAX_NUM_ORDERS"
	FILTER_TYPE_EXCHANGE_MAX_NUM_ALGO_ORDERS    FilterType = "EXCHANGE_MAX_NUM_ALGO_ORDERS"
	FILTER_TYPE_EXCHANGE_MAX_NUM_ICEBERG_ORDERS FilterType = "EXCHANGE_MAX_NUM_ICEBERG_ORDERS"
)
